<h1> Autograd</h1>

In [1]:
import torch

In [2]:
## reauires_gradをTrueにすることで全ての操作の追跡が開始する
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
## 演算を行う
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [4]:
print(y.grad_fn)

In [5]:
## yに対して多くの操作を行う
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [6]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad) #まだFalse
a.requires_grad_(True)
print(a.requires_grad) #Trueになってる
b = (a * a).sum()
print(b.grad_fn) #sumしたよっていうのが分かる

False
True


In [7]:
out.backward()

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
x = torch.randn(3, requires_grad=True)
y = x * 2
print(y)
print(y.data)
print(y.data.norm())
while y.data.norm() < 1000:
    y = y * 2
print(y.data.norm())
print(y)

tensor([1.2908, 0.6347, 1.4732], grad_fn=<MulBackward>)
tensor([1.2908, 0.6347, 1.4732])
tensor(2.0590)
tensor(1054.2076)
tensor([660.8992, 324.9492, 754.3036], grad_fn=<MulBackward>)


In [16]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([ 204.8000, 2048.0000,    0.2048])


In [19]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
