In [2]:
import torch #基本
from torch.autograd import Variable #自動微分用 <- ??
import torch.nn as nn #ネットワーク構築用 <- なんとなく
import torch.optim as optim #最適化関数 <- Adam とかそういうのかな
import torch.nn.functional as F #ネットワーク用の様々な関数 <- なぞ
import torch.utils.data #データセット読み込み関連
import torchvision #画像関連
from torchvision import datasets, models, transforms #画像データセット諸々

In [4]:
#Tensor型の定義　演算は基本これ
x = torch.Tensor(5,3) #5*3のTensorを定義
y = torch.rand(5,3) #5*3の乱数で初期化したTensorの定義
z = x + y 
print(x)
print(y)
print(z)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
tensor([[0.8414, 0.5499, 0.2028],
        [0.4868, 0.0140, 0.3279],
        [0.9587, 0.8357, 0.7299],
        [0.9565, 0.1805, 0.5505],
        [0.5364, 0.3508, 0.2639]])
tensor([[0.8414, 0.5499, 0.2028],
        [0.4868, 0.0140, 0.3279],
        [0.9587, 0.8357, 0.7299],
        [0.9565, 0.1805, 0.5505],
        [0.5364, 0.3508, 0.2639]])


In [7]:
import numpy as np
print(x)
x_np = x.numpy()
print(x_np)
x_np_tensor = torch.from_numpy(x_np)
print(x_np_tensor)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
[[  0.00000000e+00   4.65661287e-10   7.85890371e-24]
 [  1.08446622e-19   1.12103877e-44   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]]
tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [8]:
x = np.random.rand(5,3) #numpyで5*3の行列を定義　ランダムで初期化
y = torch.from_numpy(x) #numpyで定義された行列をTensorに変換
z = y.numpy() #Tensorを行列に変換
print(x)
print(y)
print(z)

[[ 0.60486297  0.52533276  0.67410172]
 [ 0.45628967  0.03435153  0.83993346]
 [ 0.85575575  0.42599568  0.59688793]
 [ 0.24939205  0.52958519  0.4921792 ]
 [ 0.36196654  0.43716254  0.44826665]]
tensor([[0.6049, 0.5253, 0.6741],
        [0.4563, 0.0344, 0.8399],
        [0.8558, 0.4260, 0.5969],
        [0.2494, 0.5296, 0.4922],
        [0.3620, 0.4372, 0.4483]], dtype=torch.float64)
[[ 0.60486297  0.52533276  0.67410172]
 [ 0.45628967  0.03435153  0.83993346]
 [ 0.85575575  0.42599568  0.59688793]
 [ 0.24939205  0.52958519  0.4921792 ]
 [ 0.36196654  0.43716254  0.44826665]]


In [9]:
#Tensor型を微分可能にするためにはVariable型にする必要がある
x = torch.rand(5,3)
y = Variable(x)
z = torch.pow(y,2) + 2 # y_i ** 2 + 2　累乗 y^2 +2
print(x)
print(y)
print(z)

tensor([[0.4009, 0.1348, 0.2366],
        [0.3089, 0.4645, 0.9304],
        [0.7421, 0.2468, 0.7325],
        [0.1424, 0.2490, 0.6009],
        [0.6437, 0.8483, 1.0000]])
tensor([[0.4009, 0.1348, 0.2366],
        [0.3089, 0.4645, 0.9304],
        [0.7421, 0.2468, 0.7325],
        [0.1424, 0.2490, 0.6009],
        [0.6437, 0.8483, 1.0000]])
tensor([[2.1608, 2.0182, 2.0560],
        [2.0954, 2.2158, 2.8657],
        [2.5507, 2.0609, 2.5366],
        [2.0203, 2.0620, 2.3611],
        [2.4144, 2.7196, 3.0000]])


In [19]:
##データの取得
##pytorchで与えるデータはTensor(train), Tensor(target)のようにする
##学習用とテスト用
X_train = np.random.rand(5,3)
y_train = np.random.rand(5,3) #Xと同じサイズじゃなきゃだめ？
X_test = np.random.rand(5,3)
y_test = np.random.rand(5,3) #Xと同じサイズじゃなきゃだめ？

train = torch.utils.data.TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
train_loader = torch.utils.data.DataLoader(train, batch_size=100,shuffle=True)
test = torch.utils.data.TensorDataset(torch.from_numpy(X_test), torch.from_numpy(y_test))
test_loader = torch.utils.data.DataLoader(test, batch_size=100, shuffle=True)

In [25]:
## torchvisionを使用することで画像処理関連(transformでTensor化、標準化、クロップなどの処理を一律に実行可能)
## CIFAR-10などのデータセットの読み込みもできる

#画像の変形処理
transform = transforms.Compose(
            [transforms.ToTensor(),
             transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))])
print(transform)

#CIFAR-10のTensorに変形前のtrainsetのロード
rawtrainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)

#CIFAR-10のtrain, testsetのロード -> 変形
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

Compose(
    ToTensor()
    Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
)
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified


In [26]:
## DataLoaderの適用->バッチの割り当て・シャッフルをまとめて実行できる
## batch_sizeでバッチサイズを指定
## num_workersで幾つのコアでデータをロードするか指定（デフォルトはメインのみ）
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True, num_workers=2)
testloaser = torch.utils.data.DataLoader(testset, batch_size=4, shuffle=False, num_workers=2)

In [27]:
## モデル定義 <- 重要
## initとforwardをクラス定義する

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784,500)
        self.fc2 = nn.Linear(500, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.relu(self.fc1(x)) #ReLU関数の使用
        x = F.relu(self.fc2(x)) #ReLU関数の使用
        x = F.log_softmax(self.fc3(x)) #softmax関数の使用
        return x
    
model = Net()

In [31]:
## 学習を行う
## Loss関数とOptimizerの定義

#Loss関数の指定
criterion = nn.CrossEntropyLoss()
#optimizerの指定
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [33]:
## Main関数の流れ

for epoch in range(2):
    running_loss = 0.0
    for i,data in enumerate(trainloader):
        inputs, labels=data
        inputs, lables=Variable(inputs),Variable(labels)
        optimizer.zero_grad()
        outputs = model(inputs)

RuntimeError: size mismatch, m1: [384 x 32], m2: [784 x 500] at /Users/soumith/code/builder/wheel/pytorch-src/aten/src/TH/generic/THTensorMath.cpp:2070