<h1> Pytorch入門 </h1>

In [48]:
from __future__ import print_function
import torch

In [9]:
x = torch.empty(5,3) #初期化されていない5*3の行列
print(x)

tensor([[ 0.0000, -2.0000,  0.0000],
        [-2.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [10]:
x = torch.rand(5,3) #ランダムに初期化された行列
print(x)

tensor([[0.4637, 0.9118, 0.4526],
        [0.5456, 0.3533, 0.1207],
        [0.4864, 0.8010, 0.2632],
        [0.8288, 0.7410, 0.4800],
        [0.1171, 0.4663, 0.4230]])


In [14]:
x = torch.zeros(5,3,dtype=torch.long) #long型の行列を0で埋める
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
x = torch.tensor([5.5,3]) #Tensorの構築
print(x)

tensor([5.5000, 3.0000])


In [20]:
x = x.new_ones(5,3,dtype=torch.double) #new_* methods take in size
print(x)
x = torch.randn_like(x,dtype=torch.float) #xの型を上書き
print(x) 
# サイズはxを維持している
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9426,  0.9213, -0.5243],
        [-1.3979, -0.3477,  0.9054],
        [-1.9180,  0.4292,  0.1225],
        [-0.1284,  0.2609,  0.8424],
        [ 0.1347, -0.2114,  0.1352]])
torch.Size([5, 3])


<h1> ~ オペレーション ~ </h1>
<h2>加算や減算を行う</h2>
<h3>１回計算するのにも種類がある</h3>

In [25]:
y = torch.rand(5,3)
## 単純に足す
print(x+y)

## add関数を使用する
print(torch.add(x,y))

## 出力をadd関数の引数として与える
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

## adds x to y
y.add_(x)
print(y)

tensor([[ 1.4678,  1.8642, -0.2186],
        [-0.8986,  0.3156,  1.5179],
        [-1.0826,  0.5941,  0.2969],
        [ 0.2477,  1.2157,  1.7932],
        [ 0.2479,  0.1986,  1.1288]])
tensor([[ 1.4678,  1.8642, -0.2186],
        [-0.8986,  0.3156,  1.5179],
        [-1.0826,  0.5941,  0.2969],
        [ 0.2477,  1.2157,  1.7932],
        [ 0.2479,  0.1986,  1.1288]])
tensor([[ 1.4678,  1.8642, -0.2186],
        [-0.8986,  0.3156,  1.5179],
        [-1.0826,  0.5941,  0.2969],
        [ 0.2477,  1.2157,  1.7932],
        [ 0.2479,  0.1986,  1.1288]])
tensor([[ 1.4678,  1.8642, -0.2186],
        [-0.8986,  0.3156,  1.5179],
        [-1.0826,  0.5941,  0.2969],
        [ 0.2477,  1.2157,  1.7932],
        [ 0.2479,  0.1986,  1.1288]])


In [26]:
## 参照の仕方
# 通常のnumpyのような索引付けが可能
print(x[:,1])

tensor([ 0.9213, -0.3477,  0.4292,  0.2609, -0.2114])


In [35]:
## サイズ変更
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # (-1,8) (-1,4) などにすることで勝手にサイズを決める
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [36]:
## item関数を使用し、値を取り出し 1要素のテンソルのみ
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0425])
-0.042535778135061264


<h2>Tensor to Numpy</h2>
<h2>Numpy to Tensor</h2>

In [45]:
## Tensor to Numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[ 1.  1.  1.  1.  1.]


In [42]:
## Numpy to Tensor
import numpy as np
c = np.ones(5)
print(c)
d = torch.from_numpy(c)
print(d)

[ 1.  1.  1.  1.  1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [46]:
a.add_(1) # <- なぞ
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


In [47]:
np.add(c, 1, out=c) # <- なぞ（cの操作でdも変わる）
print(c)
print(d)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
